<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CotizacionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cotizacion')->insert([
            [
                'id_cotizacion' => 1,
                'FechaCotizacion' => now(),
                'Nit' => '123456789',
                'Razon_Social' => 'Empresa 1',
                'Telefono' => '1234567890',
                'Correo' => 'empresa1@example.com',
                'Direccion' => 'Calle 1 #123',
                'CoStatus' => 'Pendiente',
                'sede' => 'Sede 1',
                'Transporte' => 50.00,
                'Subtotal' => 100.00,
                'Total' => 150.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_cotizacion' => 2,
                'FechaCotizacion' => now(),
                'Nit' => '987654321',
                'Razon_Social' => 'Empresa 2',
                'Telefono' => '0987654321',
                'Correo' => 'empresa2@example.com',
                'Direccion' => 'Calle 2 #456',
                'CoStatus' => 'Aceptado',
                'sede' => 'Sede 2',
                'Transporte' => 60.00,
                'Subtotal' => 200.00,
                'Total' => 260.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_cotizacion' => 3,
                'FechaCotizacion' => now(),
                'Nit' => '112233445',
                'Razon_Social' => 'Empresa 3',
                'Telefono' => '1122334455',
                'Correo' => 'empresa3@example.com',
                'Direccion' => 'Calle 3 #789',
                'CoStatus' => 'Rechazado',
                'sede' => 'Sede 3',
                'Transporte' => 70.00,
                'Subtotal' => 300.00,
                'Total' => 370.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_cotizacion' => 4,
                'FechaCotizacion' => now(),
                'Nit' => '556677889',
                'Razon_Social' => 'Empresa 4',
                'Telefono' => '5566778899',
                'Correo' => 'empresa4@example.com',
                'Direccion' => 'Calle 4 #101',
                'CoStatus' => 'Pendiente',
                'sede' => 'Sede 4',
                'Transporte' => 80.00,
                'Subtotal' => 400.00,
                'Total' => 480.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_cotizacion' => 5,
                'FechaCotizacion' => now(),
                'Nit' => '998877665',
                'Razon_Social' => 'Empresa 5',
                'Telefono' => '9988776655',
                'Correo' => 'empresa5@example.com',
                'Direccion' => 'Calle 5 #202',
                'CoStatus' => 'Aceptado',
                'sede' => 'Sede 5',
                'Transporte' => 90.00,
                'Subtotal' => 500.00,
                'Total' => 590.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('cotizacion_residuos')->insert([
            [
                'cotizacion_id' => 1,
                'RespelName' => 'Residuo 1',
                'YRespelClasf4741' => 'Clasificación 1',
                'RespelIgrosidad' => 'Peligrosidad 1',
                'Tratamiento' => 'Tratamiento 1',
                'CantidadKilos' => 10.00,
                'PrecioKg' => 5.00,
                'Subtotal' => 50.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cotizacion_id' => 2,
                'RespelName' => 'Residuo 2',
                'YRespelClasf4741' => 'Clasificación 2',
                'RespelIgrosidad' => 'Peligrosidad 2',
                'Tratamiento' => 'Tratamiento 2',
                'CantidadKilos' => 20.00,
                'PrecioKg' => 10.00,
                'Subtotal' => 200.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cotizacion_id' => 3,
                'RespelName' => 'Residuo 3',
                'YRespelClasf4741' => 'Clasificación 3',
                'RespelIgrosidad' => 'Peligrosidad 3',
                'Tratamiento' => 'Tratamiento 3',
                'CantidadKilos' => 30.00,
                'PrecioKg' => 15.00,
                'Subtotal' => 450.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cotizacion_id' => 4,
                'RespelName' => 'Residuo 4',
                'YRespelClasf4741' => 'Clasificación 4',
                'RespelIgrosidad' => 'Peligrosidad 4',
                'Tratamiento' => 'Tratamiento 4',
                'CantidadKilos' => 40.00,
                'PrecioKg' => 20.00,
                'Subtotal' => 800.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cotizacion_id' => 5,
                'RespelName' => 'Residuo 5',
                'YRespelClasf4741' => 'Clasificación 5',
                'RespelIgrosidad' => 'Peligrosidad 5',
                'Tratamiento' => 'Tratamiento 5',
                'CantidadKilos' => 50.00,
                'PrecioKg' => 20.00,
                'Subtotal' => 800.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cotizacion_id' => 5,
                'RespelName' => 'Residuo 5',
                'YRespelClasf4741' => 'Clasificación 5',
                'RespelIgrosidad' => 'Peligrosidad 5',
                'Tratamiento' => 'Tratamiento 5',
                'CantidadKilos' => 50.00,
                'PrecioKg' => 25.00,
                'Subtotal' => 1250.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}